[package]
name = "lsp"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.20", features = ["full"] }
tower-lsp = "0.20"
portpicker = "0.1"
tokio-util = { version = "0.7.15", features = ["codec"] }

serde = { version = "1", features = ["derive"] }
serde_json = "1"
